export const operationConstants = {
    GET_CURRENT_OPS_REQUEST: 'GET_CLIENT_CURRENT_OPERATIONS_REQUEST',
    GET_CURRENT_OPS_SUCCESS: 'GET_CLIENT_CURRENT_OPERATIONS_SUCCESS',
    GET_CURRENT_OPS_ERROR: 'GET_CLIENT_CURRENT_OPERATIONS_ERROR',
    GET_CURRENT_OPS_CLEAR: 'GET_CLIENT_CURRENT_OPERATIONS_CLEAR',
    GET_PAST_OPS_REQUEST: 'GET_CLIENT_PAST_OPERATIONS_REQUEST',
    GET_PAST_OPS_SUCCESS: 'GET_CLIENT_PAST_OPERATIONS_SUCCESS',
    GET_PAST_OPS_ERROR: 'GET_CLIENT_PAST_OPERATIONS_ERROR',
    GET_PAST_OPS_CLEAR: 'GET_CLIENT_PAST_OPERATIONS_CLEAR',

    UPDATE_CLIENT_OP:'UPDATE_OPERATION_BY_CLIENT',

    DELETE_CLIENT_OP:'DELETE_OPERATION_BY_CLIENT'
}

export const monthnames = ["January", "February", "March", "April", "May", "June", 
"July", "August", "September", "October", "November", "December" ]