export const operationConstants = {
    GET_FUTURE_OPS_REQUEST: 'GET_CLIENT_FUTURE_OPERATIONS_REQUEST',
    GET_FUTURE_OPS_SUCCESS: 'GET_CLIENT_FUTURE_OPERATIONS_SUCCESS',
    GET_FUTURE_OPS_ERROR: 'GET_CLIENT_FUTURE_OPERATIONS_ERROR',
    GET_FUTURE_OPS_CLEAR: 'GET_CLIENT_FUTURE_OPERATIONS_CLEAR',
    GET_PAST_OPS_REQUEST: 'GET_CLIENT_PAST_OPERATIONS_REQUEST',
    GET_PAST_OPS_SUCCESS: 'GET_CLIENT_PAST_OPERATIONS_SUCCESS',
    GET_PAST_OPS_ERROR: 'GET_CLIENT_PAST_OPERATIONS_ERROR',
    GET_PAST_OPS_CLEAR: 'GET_CLIENT_PAST_OPERATIONS_CLEAR',
}