export const tutorialConstants = {
    GETALL_REQUEST: 'TUTORIAL_GETALL_REQUEST',
    GETALL_SUCCESS: 'TUTORIAL_GETALL_SUCCESS',
    GETALL_ERROR: 'TUTORIAL_GETALL_ERROR',
    GETALL_CLEAR: 'TUTORIAL_GETALL_CLEAR'
};